name: GraphQL Testing

# Trigger deployment only on push to master branch
on:
  pull_request:

jobs:
  deploy:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v2

      - name: Install Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Run Tests
        run: pipenv run pytest -v